/** Declaration file generated by dts-gen */

declare class Mfrc522 {

    constructor(...args: any[]);

    antennaOff(...args: any[]): void;

    setBuzzerPin(...args: any[]): void;

    antennaOff(...args: any[]): void;

    antennaOn(...args: any[]): void;

    appendCRCtoBufferAndSendToCard(...args: any[]): void;

    authenticate(...args: any[]): void;

    calculateCRC(...args: any[]): void;

    clearRegisterBitMask(...args: any[]): void;

    findCard(...args: any[]): void;

    getDataForBlock(...args: any[]): void;

    getUid(...args: any[]): void;

    readRegister(...args: any[]): void;

    reset(...args: any[]): void;

    selectCard(...args: any[]): void;

    setRegisterBitMask(...args: any[]): void;

    setResetPin(...args: any[]): void;

    stopCrypto(...args: any[]): void;

    toCard(...args: any[]): void;

    writeAuthenticationKey(...args: any[]): void;

    writeDataToBlock(...args: any[]): void;

    writeRegister(...args: any[]): void;
}


declare module "mfrc522-rpi" {
    export = Mfrc522;
}