/** Declaration file generated by dts-gen */

export function addListener(type: any, listener: any): any;

export function emit(type: any, args: any): any;

export function eventNames(): any;

export function getDuration(cb: any): void;

export function getMaxListeners(): any;

export function getMaxRate(cb: any): void;

export function getMinRate(cb: any): void;

export function getPosition(cb: any): void;

export function getSource(cb: any): void;

export function getStatus(cb: any): void;

export function getVolume(cb: any): void;

export function hideSubtitles(cb: any): any;

export function hideVideo(cb: any): any;

export function increaceRate(cb: any): any;

export function listAudio(cb: any): void;

export function listSubtitles(cb: any): void;

export function listenerCount(type: any): any;

export function listeners(type: any): any;

export function nextAudio(cb: any): any;

export function nextSubtitle(cb: any): any;

export function off(type: any, listener: any): any;

export function on(type: any, listener: any): any;

export function once(type: any, listener: any): any;

export function open(path: any, options: any): void;

export function pause(cb: any): any;

export function playPause(cb: any): any;

export function prependListener(type: any, listener: any): any;

export function prependOnceListener(type: any, listener: any): any;

export function previousAudio(cb: any): any;

export function previousSubtitle(cb: any): any;

export function rawListeners(type: any): any;

export function reduceRate(cb: any): any;

export function removeAllListeners(type: any, ...args: any[]): any;

export function removeListener(type: any, listener: any): any;

export function seek(offset: any, cb: any): any;

export function selectAudio(audioStreamId: any, cb: any): any;

export function setAlpha(alpha: any, cb: any): any;

export function setAspectMode(aspect: any, cb: any): any;

export function setMaxListeners(n: any): any;

export function setPosition(pos: any, cb: any): any;

export function setVideoCropPos(x1: any, y1: any, x2: any, y2: any, cb: any): any;

export function setVideoPos(x1: any, y1: any, x2: any, y2: any, cb: any): any;

export function setVolume(vol: any, cb: any): any;

export function showSubtitles(cb: any): any;

export function stop(cb: any): any;

export function toggleSubtitles(cb: any): any;

export function unhideVideo(cb: any): any;

export function volumeDown(cb: any): any;

export function volumeUp(cb: any): any;

